spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    driver-class-name: org.postgresql.Driver
    username: monew_user
    password: monew1234
    hikari:
      connection-init-sql: SET search_path TO batch_meta, app, public

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: app

  batch:
    jdbc:
      initialize-schema: always
      table-prefix: batch_meta.BATCH_
    job:
      enabled: true

  sql:
    init:
      mode: never
      continue-on-error: true
      schema-locations:
        - classpath:schema-create.sql
        - classpath:app-schema-postgres.sql
        - classpath:batch-schema-postgres.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.jdbc.datasource.init: DEBUG

    # SQL
    org.hibernate.sql: debug # 실행된 SQL
    org.hibernate.orm.jdbc.bind: trace # 바인딩 파라미터
